#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Catatan Mekanik Kuantum  # The title of the book.
author                      : Murthadza Aznam  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Senarai pemalar dan nilai-nilai yang digunakan secara berulang-ulang
parse:
  myst_substitutions:
    pemalar_boltzmann: $1.380649\times 10^{-23} \text{J}\cdot\text{K}^{-1}$
    pemalar_stefan_boltzmann: $5.6704\times 10^{-8}\;\text{W}\cdot\text{m}^{-2}\cdot\text{K}^{-4}$
    pemalar_wien: $2.8978\times 10^{-3}\;\text{m}\cdot\text{K}$

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: mekanik-kuantum-murthadza.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/thaza-kun/mekanik-kuantum-jb  # Online location of your book
  path_to_book: mekanik-kuantum/  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax_config:
      loader:
        load: ['[tex]/physics']
      tex:
        packages:
          '[+]': ['physics']